# File generated by Flopy version 3.5.0 on 01/16/2024 at 00:12:31.
BEGIN attributes
  NAMES  flowrate
  METHODS  linearend
END attributes

BEGIN timeseries
       0.00000000    2000.00000000
     307.00000000    6000.00000000
     791.00000000    5000.00000000
    1000.00000000    9000.00000000
END timeseries

