# File generated by Flopy version 3.5.0 on 01/17/2024 at 14:11:10.
BEGIN attributes
  NAMES  chdhead
  METHODS  linearend
END attributes

BEGIN timeseries
       0.00000000       0.00000000
     307.00000000       1.00000000
     791.00000000       5.00000000
    1000.00000000       2.00000000
END timeseries

