# File generated by Flopy version 3.5.0 on 01/15/2024 at 13:29:05.
BEGIN attributes
  NAMES  rch_2
  METHODS  stepwise
END attributes

BEGIN timeseries
       0.00000000       0.00160000
       1.00000000       0.00180000
      11.00000000       0.00190000
      21.00000000       0.00160000
      31.00000000       0.00180000
END timeseries

