# File generated by Flopy version 3.5.0 on 01/14/2024 at 22:29:54.
BEGIN attributes
  NAMES  rch_2
  METHODS  stepwise
END attributes

BEGIN timeseries
       0.00000000       0.00160000
       1.00000000       0.00180000
      11.00000000       0.00190000
      21.00000000       0.00160000
      31.00000000       0.00180000
END timeseries

